name: Release workflow
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  main:
    name: Release tag
    runs-on: ubuntu-latest
    steps:
    - run: echo Release: ${GITHUB_REF}
    - run: helm version
