name: Release workflow
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  main:
    name: Release tag
    runs-on: ubuntu-latest
    steps:
    - run: echo "Release ${GITHUB_REF}"
    - run: export TAG=$(echo ${GITHUB_REF} | sed 's/refs.tags.//')
    - run: echo "Tag ${TAG}"
    - run: helm version
