name: Release workflow
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  main:
    name: Release tag
    runs-on: ubuntu-latest
    steps:
      - name: release-tag
        run: echo Release: ${GITHUB_REF}
      - name: helm-present
        run: helm version
