name: Ruby action

on: [issues]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
        repo-token: ${{ secrets.GH_ACTIONS_TOKEN }}
    - run: ruby hello.rb
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
