name: Ruby action

on: [issues]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - run: ruby hello.rb
